#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""Synchronise the local .env with the Git-tracked .env.template.

.env is local (never committed); .env.template is the variable contract in
Git. .env may hold MORE variables than the template, never fewer. The result
is rebuilt from the template layout:

  - every template variable keeps the VALUE from .env and the inline COMMENT
    from .env.template (so the file stays aligned with Git except for values);
  - template variables missing from .env are added with the template default;
  - variables only present in .env stay ACTIVE, moved to a clearly marked
    REVIEW section at the top of the file for a human to decide on;
  - a variable defined twice in .env with different values aborts the sync
    (nothing is written) until it is resolved by hand.

Usage:
  wrapper/stubs/sync_envs.py              rewrite .env when it differs (backup first)
  wrapper/stubs/sync_envs.py --dry-run    show the unified diff, write nothing
  wrapper/stubs/sync_envs.py --check      write nothing; exit 10 if a sync is needed

Every write is preceded by a .env--backup-YYYY-MM-DD copy and is atomic,
preserving the file mode and owner. Running it twice is a no-op.
Exit status: 0 in sync / written, 10 sync needed (--check, --dry-run), 1 error.
"""

from __future__ import annotations

import sys

sys.dont_write_bytecode = True  # never write __pycache__ into the worktree

import argparse
import difflib
import os
import re
import shutil
import tempfile
from dataclasses import dataclass, field
from datetime import date, datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
EXIT_SYNC_NEEDED = 10

ASSIGN_RE = re.compile(r"^(?P<prefix>\s*(?:export\s+)?)(?P<key>[A-Za-z_][A-Za-z0-9_]*)=(?P<raw>.*)$")
PLACEHOLDER_RE = re.compile(r"PUT_YOUR_|CHANGE_ME")

BAR = "#" * 72
REVIEW_HEADER = [
    BAR,
    "# REVIEW REQUIRED - variables present in .env but NOT in .env.template",
    "#",
    "# They are still ACTIVE (the stacks keep reading them). For each one,",
    "# either add it to .env.template and commit it, or delete it here.",
    "# This section is regenerated by wrapper/stubs/sync_envs.py on every run.",
    BAR,
]
REVIEW_FOOTER = [
    BAR,
    "# END OF REVIEW SECTION",
    BAR,
    "",
]


class SyncError(Exception):
    """The files cannot be synchronised automatically; nothing was written."""


# --------------------------------------------------------------------------
# parsing
# --------------------------------------------------------------------------

def split_raw(raw: str) -> tuple[str, str]:
    """Split the text after '=' into (value, inline comment incl. leading blanks)."""
    raw = raw.rstrip()
    if raw[:1] in ("'", '"'):
        end = raw.find(raw[0], 1)
        if end != -1:
            return raw[: end + 1], raw[end + 1:]
    match = re.match(r"^(.*?)(\s+#.*)?$", raw)
    return match[1], match[2] or ""


def unquote(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
        return value[1:-1]
    return value


@dataclass
class Assignment:
    lineno: int
    prefix: str
    key: str
    value: str      # as written (quotes kept)
    comment: str    # inline comment incl. leading blanks, or ""


@dataclass
class DotEnv:
    path: Path
    lines: list[str]
    order: list[str] = field(default_factory=list)
    entries: dict[str, list[Assignment]] = field(default_factory=dict)

    @classmethod
    def load(cls, path: Path) -> DotEnv:
        if not path.is_file():
            raise SyncError(f"not found: {path}")
        env = cls(path, path.read_text(encoding="utf-8").splitlines())
        for number, line in enumerate(env.lines, start=1):
            match = ASSIGN_RE.match(line)
            if not match:
                continue
            value, comment = split_raw(match["raw"])
            item = Assignment(number, match["prefix"], match["key"], value, comment)
            if item.key not in env.entries:
                env.order.append(item.key)
                env.entries[item.key] = []
            env.entries[item.key].append(item)
        return env

    def conflicts(self) -> dict[str, list[Assignment]]:
        """Keys defined more than once with different (unquoted) values."""
        return {
            key: items for key, items in self.entries.items()
            if len({unquote(item.value) for item in items}) > 1
        }

    def repeated(self) -> list[str]:
        return [key for key, items in self.entries.items() if len(items) > 1]

    def last(self, key: str) -> Assignment:
        return self.entries[key][-1]


# --------------------------------------------------------------------------
# synchronisation
# --------------------------------------------------------------------------

@dataclass
class SyncResult:
    current: str
    text: str
    new: list[str]
    extra: list[str]
    collapsed: list[str]
    placeholders: list[str]

    @property
    def changed(self) -> bool:
        return self.text != self.current


def _describe(key: str, items: list[Assignment], path: Path) -> str:
    where = ", ".join(f"line {item.lineno}: {item.value!r}" for item in items)
    return f"  {key} ({path.name}) -> {where}"


def plan(env_path: Path, tpl_path: Path) -> SyncResult:
    """Compute the synchronised .env text. Raises SyncError; never writes."""
    tpl = DotEnv.load(tpl_path)
    env = DotEnv.load(env_path)

    problems: list[str] = []
    for key in tpl.repeated():
        problems.append(_describe(key, tpl.entries[key], tpl.path))
    for key, items in env.conflicts().items():
        problems.append(_describe(key, items, env.path))
    if problems:
        raise SyncError(
            "variables defined more than once; resolve them by hand and run again:\n"
            + "\n".join(problems)
        )

    new = [key for key in tpl.order if key not in env.entries]
    extra = [key for key in env.order if key not in tpl.entries]

    out: list[str] = []
    if extra:
        out += REVIEW_HEADER
        for key in extra:
            item = env.last(key)
            out.append(f"{item.prefix}{key}={item.value}{item.comment}")
        out += REVIEW_FOOTER

    for line in tpl.lines:
        match = ASSIGN_RE.match(line)
        if not match:
            out.append(line)
            continue
        key = match["key"]
        tpl_value, tpl_comment = split_raw(match["raw"])
        value = env.last(key).value if key in env.entries else tpl_value
        out.append(f"{match['prefix']}{key}={value}{tpl_comment}")

    current = "\n".join(env.lines).rstrip() + "\n" if env.lines else ""
    text = "\n".join(out).rstrip() + "\n"
    placeholders = [key for key in new if PLACEHOLDER_RE.search(tpl.last(key).value)]
    return SyncResult(current, text, new, extra, env.repeated(), placeholders)


def backup_env(env_path: Path) -> Path:
    """Copy .env to .env--backup-YYYY-MM-DD; never overwrite an earlier copy."""
    backup = env_path.with_name(f"{env_path.name}--backup-{date.today().isoformat()}")
    if backup.exists():
        backup = backup.with_name(f"{backup.name}-{datetime.now():%H%M%S}")
    shutil.copy2(env_path, backup)
    return backup


def write_atomic(path: Path, text: str) -> None:
    existing = path.stat()
    handle = tempfile.NamedTemporaryFile("w", dir=path.parent, delete=False, encoding="utf-8")
    try:
        with handle:
            handle.write(text)
        os.chmod(handle.name, existing.st_mode & 0o7777)
        if os.geteuid() == 0:
            os.chown(handle.name, existing.st_uid, existing.st_gid)
        os.replace(handle.name, path)
    except BaseException:
        Path(handle.name).unlink(missing_ok=True)
        raise


def apply(env_path: Path, result: SyncResult) -> Path | None:
    """Write the result (backup first). Returns the backup path, or None if unchanged."""
    if not result.changed:
        return None
    backup = backup_env(env_path)
    write_atomic(env_path, result.text)
    return backup


def report(result: SyncResult, out=sys.stdout) -> None:
    if result.new:
        print(f"New variables taken from the template ({len(result.new)}): {', '.join(result.new)}", file=out)
    if result.extra:
        print(f"Variables only in .env, kept ACTIVE in the REVIEW section ({len(result.extra)}): "
              f"{', '.join(result.extra)}", file=out)
    if result.collapsed:
        print(f"Repeated with the same value, kept once: {', '.join(result.collapsed)}", file=out)
    if result.placeholders:
        print(f"WARNING: new variables that need a real value: {', '.join(result.placeholders)}",
              file=sys.stderr)


# --------------------------------------------------------------------------
# command line
# --------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__.splitlines()[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--env", type=Path, default=REPO_ROOT / ".env",
                        help="local .env (default: repository root)")
    parser.add_argument("--template", type=Path, default=REPO_ROOT / ".env.template",
                        help="Git-tracked template (default: repository root)")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="write nothing; exit 10 if a sync is needed")
    mode.add_argument("--dry-run", action="store_true", help="print the unified diff; write nothing")
    args = parser.parse_args(argv)

    env_path = args.env.expanduser().resolve()
    tpl_path = args.template.expanduser().resolve()
    try:
        result = plan(env_path, tpl_path)
    except SyncError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1

    if not result.changed:
        print(f"{env_path.name} is already in sync with {tpl_path.name}.")
        return 0

    report(result)
    if args.check:
        print(f"{env_path.name} needs a sync; run wrapper/stubs/sync_envs.py")
        return EXIT_SYNC_NEEDED
    if args.dry_run:
        sys.stdout.writelines(difflib.unified_diff(
            result.current.splitlines(keepends=True), result.text.splitlines(keepends=True),
            fromfile=str(env_path), tofile=f"{env_path} (synced)",
        ))
        return EXIT_SYNC_NEEDED

    backup = apply(env_path, result)
    print(f"{env_path} synchronised. Backup: {backup}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
